name: chat-app-dev-env
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pytest
  - pip
  - awscli
  - pip:
    - langchain>=0.1.0
    - langchain-aws>=0.1.0
    - langchain-community>=0.0.20
    - boto3>=1.34.0
    - psycopg2-binary>=2.9.9
    - pyyaml>=6.0.1
