name: chat-template-env
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pytest
  - pyaml
  - awscli
  - boto3
  - pip:
    - -r src/rag_lambda/requirements.txt
    - -r evals/requirements.txt
# Note: PYTHONPATH is automatically set to the project root via an activation script
# created by scripts/setup_env.sh when the environment is created/updated
